server:
  port: 8282
  error:
    path: /user/error
    whitelabel:
      enabled: false
#  servlet:
#    context-path: /bddproject
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contactdb
    #url: jdbc:mysql://google/asmahan_db?cloudSqlInstance=spring-boot-db-project:europe-west9:mydb&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000

# Configure the logging we want
#logging:
#  level:
#    root: warn
#    com.shopme: debug

# Specify the package to log
#logging:
#  file:
#    name: Shopme-backend.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: Shopme-backend-%d{yyyy-MM-dd}.%i.log
#      max-file-size: 100KB
#      total-size-cap: 1MB
#      max-history: 14
#      clean-history-on-start: true
